# Generated by Django 5.1.5 on 2025-02-01 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='employee',
        ),
    ]
